name: Debug Build

on:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ ( startsWith(matrix.os, 'ubuntu') && 'Linux' ) ||
              ( startsWith(matrix.os, 'windows') && 'Windows' ) ||
              ( startsWith(matrix.os, 'mac') && 'macOS' ) }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - name: Download dependencies (Linux only)
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: |
        sudo apt-get update
        sudo apt-get install -y libpango1.0-dev libx11-dev libxext-dev \
                                libxft-dev libxinerama-dev libxcursor-dev \
                                libxrender-dev libxfixes-dev ninja-build
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Build
      run: |
        cargo lint
        cargo build
        cargo build --release
        if [ ${{ startsWith(matrix.os, 'windows') }} ]; then
          mv target/debug/eiri.exe eiri-debug.exe
          mv target/release/eiri.exe eiri-release.exe
        else
          mv target/debug/eiri eiri-debug
          mv target/release/eiri eiri-release
        fi
    - name: Upload the binary
      uses: actions/upload-artifact@v2
      with:
        name: ${{ ( startsWith(matrix.os, 'ubuntu') && 'Linux' ) ||
                  ( startsWith(matrix.os, 'windows') && 'Windows' ) ||
                  ( startsWith(matrix.os, 'macOS') && 'macOS' ) }}
        path: |
          eiri-debug
          eiri-debug.exe
          eiri-release
          eiri-release.exe
