version: 1
AppDir:
  path: AppDir
  app_info:
    id: io.github.paveloom.eiri
    name: Eiri
    icon: eiri
    version: 0.1.0
    exec: usr/bin/eiri
    exec_args: $@
  apt:
    arch:
    - amd64
    allow_unauthenticated: true
    sources:
      - sourceline: 'deb [arch=amd64] http://azure.archive.ubuntu.com/ubuntu bionic main restricted universe multiverse'
      - sourceline: 'deb [arch=amd64] http://azure.archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse'
    include:
    - libc6:amd64
AppImage:
  arch: x86_64
  update-information: guess
