version: 1
AppDir:
  path: AppDir
  app_info:
    id: io.github.paveloom.eiri
    name: Eiri
    icon: eiri
    version: 0.1.0
    exec: usr/bin/eiri
    exec_args: $@
  apt:
    arch:
      - amd64
    allow_unauthenticated: true
    sources:
      - sourceline: deb http://azure.archive.ubuntu.com/ubuntu/ bionic main restricted
      - sourceline: deb http://azure.archive.ubuntu.com/ubuntu/ bionic-updates main restricted
      - sourceline: deb http://azure.archive.ubuntu.com/ubuntu/ bionic universe
      - sourceline: deb http://azure.archive.ubuntu.com/ubuntu/ bionic-updates universe
      - sourceline: deb http://azure.archive.ubuntu.com/ubuntu/ bionic multiverse
      - sourceline: deb http://azure.archive.ubuntu.com/ubuntu/ bionic-updates multiverse
      - sourceline: deb http://azure.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
      - sourceline: deb http://security.ubuntu.com/ubuntu bionic-security main restricted
      - sourceline: deb http://security.ubuntu.com/ubuntu bionic-security universe
      - sourceline: deb http://security.ubuntu.com/ubuntu bionic-security multiverse
      - sourceline: deb http://ppa.launchpad.net/ondrej/php/ubuntu bionic main
      - sourceline: deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic main
      - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main
    include:
      - libc6:amd64
AppImage:
  arch: x86_64
  update-information: guess
